<a href="https://colab.research.google.com/github/yfpang7/dataScience_Practice/blob/main/vega_altair.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import plotly.express as px
import numpy as np

from vega_datasets import data
import altair as alt

In [2]:
# import the data
cars_data = data.cars()

In [3]:
cars_data.head()

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA

In [4]:
import altair as alt
from vega_datasets import data

# Load the dataset
cars_data = data.cars()

# Define the title with subtitle
title = alt.TitleParams(
    'Test', subtitle=['sub', 'title'], anchor='middle', subtitleColor='Blue'
)

# Scatter plot
scatter_plot = (
    alt.Chart(cars_data, title=title)
    .mark_point(filled=False, opacity=0.6, size=15)
    .encode(
        x=alt.X('Horsepower:Q', axis=alt.Axis(title='Horsepower')),
        y=alt.Y(
            'Miles_per_Gallon:Q',
            axis=alt.Axis(title='Miles_per_Gallon', titleFontSize=15, labelFontSize=10),
            scale=alt.Scale(domain=[0, 50]),
        ),
        color=alt.Color('Cylinders:N', legend=alt.Legend(orient='left'), scale=alt.Scale(scheme='set1')),
        shape=alt.Shape('Origin:N', legend=alt.Legend(orient='left')),
        tooltip=['Name:N', 'Cylinders:N']
    )
    .properties(width=500, height=300)
    .interactive()
)

# Box plot with median annotations
box_plot = (
    alt.Chart(cars_data)
    .mark_boxplot()
    .encode(
        x=alt.X('Cylinders:N'),
        y=alt.Y('Miles_per_Gallon:Q')
    )
    .properties(width=500, height=300)
)

# Calculate the median for each cylinder group
median_text = (
    alt.Chart(cars_data)
    .mark_text(dx=20, color='black')  # Position the text slightly above the box plot
    .encode(
        x=alt.X('Cylinders:N', axis=alt.Axis(labelAngle=0)),
        y=alt.Y('median(Miles_per_Gallon):Q'),
        text=alt.Text('median(Miles_per_Gallon):Q', format='.1f')  # Format to 1 decimal place
    )
)

# Combine the scatter plot and the box plot with median annotations
final_chart = scatter_plot | (box_plot + median_text)
final_chart

alt.HConcatChart(...)

In [5]:
# to replicate this on Plotly express
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from vega_datasets import data

# Load the dataset
cars_data = data.cars()

# Scatter plot
scatter_fig = px.scatter(
    cars_data,
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Cylinders',
    symbol='Origin',
    size_max=15,
    opacity=0.6,
    title='Test<br><sup>sub title</sup>'
)

# Update layout for scatter plot
scatter_fig.update_layout(
    xaxis_title='Horsepower',
    yaxis_title='Miles per Gallon',
    yaxis=dict(range=[0, 50], title_font=dict(size=15), tickfont=dict(size=10)),
    title_x=0.5,
    legend=dict(x=-0.3, y=0.5, title_text="Legend"),  # Move legend to the left
    title_font_color="blue"
)

# Box plot with median annotations
box_fig = px.box(
    cars_data,
    x='Cylinders',
    y='Miles_per_Gallon',
    points='all'  # Show all points to match Altair's interactivity
)

# Calculate median values for each cylinder group for annotation
median_values = cars_data.groupby('Cylinders')['Miles_per_Gallon'].median().reset_index()

# Add median annotations
for i, row in median_values.iterrows():
    box_fig.add_trace(
        go.Scatter(
            x=[row['Cylinders']],
            y=[row['Miles_per_Gallon']],
            text=f"{row['Miles_per_Gallon']:.1f}",
            mode="text",
            textposition="top center",
            showlegend=False
        )
    )

# Set layout for box plot
box_fig.update_layout(
    xaxis_title='Cylinders',
    yaxis_title='Miles per Gallon',
)

# Combine scatter and box plot in a subplot
# Create subplot figure
combined_fig = make_subplots(rows=1, cols=2, subplot_titles=("Scatter Plot", "Box Plot with Medians"))

# Add scatter plot
for trace in scatter_fig['data']:
    combined_fig.add_trace(trace, row=1, col=1)

# Add box plot with median annotations
for trace in box_fig['data']:
    combined_fig.add_trace(trace, row=1, col=2)

# Set combined layout
combined_fig.update_layout(
    width=1000, height=400,
    title_text='Combined Plot',
    template='ggplot2',
    legend=dict(
        orientation="v",  # Vertical orientation
        yanchor="top",  # Anchor top of legend
        y=0.9,  # Position legend near the top
        xanchor="left",  # Anchor legend to the left
        x=0.1,  # Adjust horizontal position as needed
        title_text="Legend"
    )
)

combined_fig.show()

combined_fig.show()

In [6]:
# plot the scatter plot
# title = alt.TitleParams('Test', subtitle='sub title', anchor='middle')
title = alt.TitleParams('Test', subtitle=['sub', 'title'], anchor='middle', subtitleColor='Blue') # this one is title breakpoint

(
    alt.Chart(
        cars_data,
        title=title,
    )
    .mark_point(filled=False, opacity=0.6)
    .encode(
        x=alt.X('Horsepower:Q', axis=alt.Axis(title='Horsepower')),
        # Move the scale definition to alt.Y
        # y=alt.Y('Miles_per_Gallon:Q', axis=alt.Axis(title='Miles_per_Gallon (log10)'), scale=alt.Scale(type='log')),
        y=alt.Y('Miles_per_Gallon:Q', axis=alt.Axis(title='Miles_per_Gallon (symlog)'), scale=alt.Scale(type='symlog')),
        color=alt.Color('Cylinders:N', legend=alt.Legend(orient='left')),
        shape=alt.Shape('Origin:N', legend=alt.Legend(orient='left'))
    )
    .properties(width=500, height=300)
    .interactive()
    .encode(tooltip=['Name:N', 'Cylinders:N'])

)

alt.Chart(...)

In [7]:
# selection by adding brush

# brush = alt.selection(type='interval')
brush = alt.selection_interval(resolve='intersect')

points = (
    alt.Chart(cars_data)
    .mark_point()
    .encode(
        x=alt.X('Horsepower:Q', axis=alt.Axis(title='Horsepower')),
        y=alt.Y('Miles_per_Gallon:Q', axis=alt.Axis(title='Miles_per_Gallon')),
        color=alt.condition(brush, if_true='Origin:N', if_false=alt.value('lightgray')),
        tooltip=['Name:N', 'Cylinders:N']
    )
    .add_selection(brush)
)

points | points.encode(x=alt.X('Weight_in_lbs:Q'), y=alt.Y('Acceleration:Q'))

/tmp/ipython-input-830926158.py:15: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use add_params instead.

alt.HConcatChart(...)

In [8]:
import altair as alt

# Setting up a ggplot2-like theme in Altair
ggplot2_theme = {
    'config': {
        'background': 'white',
        'title': {'fontSize': 16, 'font': 'Helvetica', 'color': 'black', 'anchor': 'start'},
        'axis': {
            'domain': False,
            'tickColor': 'gray',
            'labelFont': 'Helvetica',
            'labelFontSize': 12,
            'titleFont': 'Helvetica',
            'titleFontSize': 12,
            'titleColor': 'black',
            'gridColor': 'lightgray',
            'gridWidth': 0.8
        },
        'legend': {
            'labelFont': 'Helvetica',
            'labelFontSize': 12,
            'titleFont': 'Helvetica',
            'titleFontSize': 12
        },
        'mark': {
            'color': 'black',
            'fill': 'black',
            'strokeWidth': 1
        }
    }
}

# Apply theme
alt.themes.register('ggplot2_theme', lambda: ggplot2_theme)
alt.themes.enable('ggplot2_theme')

# Selection brush
brush = alt.selection_interval(resolve='intersect')

# Define the main chart with the ggplot2-like theme
points = (
    alt.Chart(cars_data)
    .mark_point()
    .encode(
        x=alt.X('Horsepower:Q', axis=alt.Axis(title='Horsepower')),
        y=alt.Y('Miles_per_Gallon:Q', axis=alt.Axis(title='Miles per Gallon')),
        color=alt.condition(brush, 'Origin:N', alt.value('lightgray')),
        tooltip=['Name:N', 'Cylinders:N']
    )
    .add_selection(brush)
)

# Combine both charts with ggplot2-like theme applied
(points | points.encode(x=alt.X('Weight_in_lbs:Q'), y=alt.Y('Acceleration:Q')))

/tmp/ipython-input-4197918447.py:34: AltairDeprecationWarning:


Deprecated since `altair=5.5.0`. Use altair.theme instead.
Most cases require only the following change:

    # Deprecated
    alt.themes.enable('quartz')

    # Updated
    alt.theme.enable('quartz')

If your code registers a theme, make the following change:

    # Deprecated
    def custom_theme():
        return {'height': 400, 'width': 700}
    alt.themes.register('theme_name', custom_theme)
    alt.themes.enable('theme_name')

    # Updated
    @alt.theme.register('theme_name', enable=True)
    def custom_theme():
        return alt.theme.ThemeConfig(
            {'height': 400, 'width': 700}
        )

See the updated User Guide for further details:
    https://altair-viz.github.io/user_guide/api.html#theme
    https://altair-viz.github.io/user_guide/customization.html#chart-themes

/tmp/ipython-input-4197918447.py:50: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use add_params instead.

alt.HConcatChart(...)

In [9]:
iris_dataset = data.iris()

iris_dataset.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [10]:
iris_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sepalLength  150 non-null    float64
 1   sepalWidth   150 non-null    float64
 2   petalLength  150 non-null    float64
 3   petalWidth   150 non-null    float64
 4   species      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [11]:
numerical_columns = iris_dataset.select_dtypes(include=['number']).columns.to_list()

(
    alt.Chart(iris_dataset)
    .mark_bar()
    .encode(
        x=alt.X(alt.repeat(), type='quantitative', bin=alt.Bin(maxbins=10)),
        y='count()',
    )
    .properties(width=200, height=200)

).repeat(numerical_columns)

alt.RepeatChart(...)

In [12]:
point = (
    alt.Chart(iris_dataset)
    .mark_point()
    .encode(
        x=alt.X('sepalWidth', title='Sepal Width'),
        y=alt.Y('sepalLength', title='Sepal Length'),
        shape=alt.Shape('species:N', title='Species', legend=alt.Legend(orient='left')),
        color=alt.Color('species:N', title='Species', legend=alt.Legend(orient='left')),
    )
)

point

alt.Chart(...)

In [13]:
# heat map
(
    alt.Chart(iris_dataset)
    .mark_circle()
    .encode(
        alt.X('sepalWidth:Q', bin=alt.Bin(maxbins=10)),
        alt.Y('sepalLength:Q', bin=alt.Bin(maxbins=10)),
        color=alt.Color('count()', scale=alt.Scale(scheme='greenblue')),
        size=alt.Size('count()', scale=alt.Scale(scheme='greenblue')),
    )
    .properties(width=500, height=400)


)

alt.Chart(...)

In [14]:
# heat map
(
    alt.Chart(iris_dataset)
    .mark_rect()
    .encode(
        alt.X('sepalWidth:Q', bin=alt.Bin(maxbins=10)),
        alt.Y('sepalLength:Q', bin=alt.Bin(maxbins=10)),
        color=alt.Color('count()', scale=alt.Scale(scheme='greenblue')),
        size=alt.Size('count()', scale=alt.Scale(scheme='greenblue')),
    )
    .properties(width=500, height=400)


)

alt.Chart(...)

In [15]:
import plotly.express as px

# Assuming iris_dataset is your DataFrame
fig = px.density_heatmap(
    data_frame=iris_dataset,
    x='sepalWidth',
    y='sepalLength',
    nbinsx=10,          # Number of bins along x-axis
    nbinsy=10,          # Number of bins along y-axis
    color_continuous_scale='RdBu_R',  # Color scale to match the scheme
    text_auto=True
)

# Customize layout
fig.update_layout(
    width=500,
    height=400,
    coloraxis_colorbar=dict(
        title='Count'
    ),
    font=dict(size=8)
)

fig.show()

In [16]:
numerical_columns = iris_dataset.select_dtypes(include=['number']).columns.to_list()


(
    alt.Chart(iris_dataset)
    .mark_rect()
    .encode(
        x=alt.X(alt.repeat('column'), type='quantitative', bin=alt.Bin(maxbins=20)),
        y=alt.Y(alt.repeat('row'), type='quantitative', bin=alt.Bin(maxbins=20)),
        color=alt.Color('count()', scale=alt.Scale(scheme='greenblue')),
    )
    .properties(width=200, height=200)
    .repeat(column=numerical_columns, row=numerical_columns)
)

alt.RepeatChart(...)

In [17]:
(
    alt.Chart(iris_dataset)
    .mark_rect()
    .encode(
        x=alt.X('species:N'),
        y=alt.Y('sepalWidth:Q', bin=alt.Bin(maxbins=30), ),
        color=alt.Color('count()', scale=alt.Scale(scheme='greenblue')),
    )
    .properties(width=200, height=500)
)

alt.Chart(...)

In [18]:
iris_dataset.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [19]:
# scatter matrix

brush = alt.selection(type='interval')
# brush = alt.selection_interval(resolve='intersect')

scatter_matrix = (
    alt.Chart(iris_dataset)
    .mark_point(opacity=0.5)
    .encode(
        x=alt.X(alt.repeat('column'), type='quantitative',),
        y=alt.Y(alt.repeat('row'), type='quantitative'),
        color=alt.condition(brush, 'species:N', alt.value('lightgrey'), legend=alt.Legend(orient='left'), scale=alt.Scale(scheme='set1')),
        size=alt.Size('petalWidth', legend=alt.Legend(orient='left'), scale=alt.Scale(range=[0,100])),
    )
    .properties(width=200, height=200)
    .repeat(
        row=['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth'],
        column=['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth'],
    )
).add_selection(brush)


scatter_matrix

/tmp/ipython-input-2692547078.py:3: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use 'selection_point()' or 'selection_interval()' instead.
These functions also include more helpful docstrings.

/tmp/ipython-input-2692547078.py:20: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use add_params instead.

alt.RepeatChart(...)

In [20]:
# explore relationship between categorcal and numerical columns
catergorical_columns = iris_dataset.select_dtypes(include=['object']).columns.to_list()
numerical_columns = iris_dataset.select_dtypes(include=['number']).columns.to_list()

(
    alt.Chart(iris_dataset)
    .mark_boxplot()
    .encode(
        y=alt.Y('species:N', title=''),
        x=alt.X(alt.repeat('column'), type='quantitative'),
    )
    .properties(width=200, height=200)
    .repeat(
        column=numerical_columns,
    )

)

alt.RepeatChart(...)

In [21]:
(
    alt.Chart(iris_dataset)
    .mark_point()
    .encode(
        x=alt.X('species:N', title='Sepal Length'),
        y=alt.Y('sepalWidth:Q', title='Sepal Width'),
        color=alt.Color('species:N', title='Species', legend=alt.Legend(orient='left')),
        column=alt.Column('species:N', title=''),
    )
    .properties(width=200, height=200)
)

alt.Chart(...)

In [22]:
import altair as alt
import pandas as pd

# Assuming cars_data is a DataFrame and it already contains the necessary columns

# Create the horsepower line chart
horsepower_line = (
    alt.Chart(cars_data)
    .encode(
        x=alt.X('Year:T'),
        y=alt.Y(
            'Horsepower:Q',
            axis=alt.Axis(title='Horsepower', titleColor='blue'),  # Set title color
            aggregate='mean'
        )
    )
    .mark_line(color='blue')  # Line color
)

# Create the weight line chart
weight_line = (
    alt.Chart(cars_data)
    .encode(
        x=alt.X('Year:T'),
        y=alt.Y(
            'Weight_in_lbs:Q',
            axis=alt.Axis(title='Weight in lbs', titleColor='orange'),  # Set title color
            aggregate='mean'
        )
    )
    .mark_line(color='orange')  # Line color
)

# Combine the two charts with independent y-axes
chart = alt.layer(horsepower_line, weight_line).resolve_scale(y='independent')

chart

alt.LayerChart(...)

In [23]:

# Assuming cars_data is a DataFrame
cars_data['Cylinders_Category'] = np.where(cars_data['Cylinders'] > 4, '> 4 Cylinders', '< 4 Cylinders')

# Create the scatter plot
scatter_plot = (
    alt.Chart(cars_data)
    .mark_circle(size=60)  # Adjust size as needed
    .encode(
        x=alt.X('Year:T', title='Year', scale=alt.Scale(domain=['1969', '1983'])),
        y=alt.Y('Horsepower:Q', title='Horsepower'),
        color=alt.Color('Cylinders_Category:N', title='Cylinders'),
        tooltip=['Name:N', 'Cylinders:N']
    )
    .properties(
        width=800,
        height=400
    )


)

scatter_plot + scatter_plot.mark_line().encode(y=alt.Y('Horsepower:Q', aggregate='mean'))

alt.LayerChart(...)

In [24]:
cars_data.head()

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin,Cylinders_Category
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA,> 4 Cylinders
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA,> 4 Cylinders
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA,> 4 Cylinders
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA,> 4 Cylinders
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA,> 4 Cylinders

In [25]:
box = (
    alt.Chart(cars_data)
    .mark_boxplot()
    .encode(
        x=alt.X('Origin:N', ),
        y=alt.Y('Horsepower:Q', ),
        color=alt.Color('Origin:N'),
        column=alt.Column('Cylinders:N', ),
    )
    .interactive()
    .properties(width=100, height=200)
)

box

alt.Chart(...)

In [26]:
import plotly.express as px
import pandas as pd

fig = px.box(
    cars_data,
    x='Origin',
    y='Horsepower',
    color='Origin',
    title='Box Plot of Horsepower by Origin and Cylinders',
    facet_col='Cylinders',
    points='all',
    hover_data=['Name', 'Cylinders'],
    width=800
)

fig.update_layout(template='ggplot2')
fig.update_traces(marker_size=4, jitter=0.5,)

fig.show()

In [27]:
url = 'https://www.bbc.co.uk/sport/football/premier-league/table'

premier_league_data = pd.read_html(url)[0]

split_last_6_games = (
    premier_league_data.rename(columns={'Form, Last 6 games, Oldest first': 'last_six_results'})
    ['last_six_results']
    .str.replace('Result', '')
    .str.replace('Win', '')
    .str.replace('Loss', '')
    .str.replace('Draw', '')
    .str.split(' ', expand=True)
    # Rename the columns of split_last_6_games to strings
    .rename(columns=lambda x: f'last_six_{x}')
)

premier_league_table = (
    premier_league_data.drop(columns=['Form, Last 6 games, Oldest first'])
    .join(split_last_6_games)
)

# inspect the data
premier_league_table.head()

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,last_six_0,last_six_1,last_six_2,last_six_3,last_six_4,last_six_5,last_six_6
0,1Liverpool,5,5,0,0,11,5,6,15,No,W,W,W,W,W,
1,2Tottenham Hotspur,5,3,1,1,10,3,7,10,No,W,W,L,W,D,
2,3Arsenal,4,3,0,1,9,1,8,9,No,No,W,W,L,W,
3,4Crystal Palace,5,2,3,0,6,2,4,9,No,D,D,W,D,W,
4,5AFC Bournemouth,4,3,0,1,6,5,1,9,No,No,L,W,W,W,

In [28]:
premier_league_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Team             20 non-null     object
 1   Played           20 non-null     int64
 2   Won              20 non-null     int64
 3   Drawn            20 non-null     int64
 4   Lost             20 non-null     int64
 5   Goals For        20 non-null     int64
 6   Goals Against    20 non-null     int64
 7   Goal Difference  20 non-null     int64
 8   Points           20 non-null     int64
 9   last_six_0       20 non-null     object
 10  last_six_1       20 non-null     object
 11  last_six_2       20 non-null     object
 12  last_six_3       20 non-null     object
 13  last_six_4       20 non-null     object
 14  last_six_5       20 non-null     object
 15  last_six_6       20 non-null     object
dtypes: int64(8), object(8)
memory usage: 2.6+ KB

In [29]:
bar = (
    alt.Chart(premier_league_table)
    .mark_bar()
    .encode(
      y=alt.Y('Team:N', title='Team', sort='-x'),
      x=alt.X('Points:Q', title='Points',),
      color=alt.Color('Team:N', title='Team', legend=None, scale=alt.Scale(scheme='category20')),
    )
)

bar

alt.Chart(...)

In [30]:
# create a scatter matrix

brush = alt.selection(type='interval')
# brush = alt.selection_interval(resolve='intersect')

numerical_data_columns = premier_league_table.select_dtypes(include=['number']).columns.to_list()

chart = (
    alt.Chart(premier_league_table)
    .mark_circle(size=30)
    .encode(
        x=alt.X(alt.repeat('column'), type='quantitative'),
        y=alt.Y(alt.repeat('row'), type='quantitative'),
        color=alt.condition(brush, 'Team:N', alt.value('lightgrey'), legend=alt.Legend(orient='left'), scale=alt.Scale(scheme='tableau20')),
        # color=alt.Color('Team:N', legend=alt.Legend(orient='left')), # removed tooltip from here
        tooltip=[ # added tooltip encoding here
            alt.Tooltip('Team:N', title='Team'),
            alt.Tooltip(alt.repeat('column'), type='quantitative'),
            alt.Tooltip(alt.repeat('row'), type='quantitative')
        ]
    )
    .properties(width=100, height=100)
    .repeat(column=numerical_data_columns, row=numerical_data_columns, spacing=0.2)
    .add_selection(brush)
)

chart

/tmp/ipython-input-782240183.py:3: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use 'selection_point()' or 'selection_interval()' instead.
These functions also include more helpful docstrings.

/tmp/ipython-input-782240183.py:24: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use add_params instead.

alt.RepeatChart(...)

In [31]:
import altair as alt

point = (
    alt.Chart(premier_league_table)
    .mark_circle()
    .encode(
        x=alt.X('Goals For:Q', axis=alt.Axis(title='Goals')),
        y=alt.Y('Goals Against:Q', axis=alt.Axis(title='Conceded')),
        size=alt.Size('Points:Q', legend=alt.Legend(orient='right')),
        color=alt.Color('Team:N', legend=None, scale=alt.Scale(scheme='tableau20')),
        tooltip=[
            alt.Tooltip('Team:N', title='Team'),
            alt.Tooltip('Goals For:Q', title='Goals For'),
            alt.Tooltip('Goals Against:Q', title='Goals Against'),
            alt.Tooltip('Points:Q', title='Points')
        ]
    )
    .properties(width=400, height=200)
)

bar = (
    alt.Chart(premier_league_table)
    .mark_bar()
    .encode(
        y=alt.Y('Team:N', title='Team', sort='-x'),
        x=alt.X('Points:Q', title='Points'),
        color=alt.Color('Team:N', title='Team', legend=None, scale=alt.Scale(scheme='tableau20')),
    )
)

# Combine the point and bar charts
(bar | point).resolve_scale(color='independent')

alt.HConcatChart(...)

In [32]:
import altair as alt
import pandas as pd

# Sample DataFrame (replace with your actual data)
data = pd.DataFrame({
    'value': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3, 4, 5, 6, 7, 2, 3, 4, 5, 1],
    'type': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'B']
})

# KDE plot with color by 'type'
kde_plot = (
    alt.Chart(data)
    .transform_density(
        density='value',
        groupby=['type'],
        as_=['value', 'density']
    )
    .mark_area(opacity=0.5)
    .encode(
        x=alt.X('value:Q', title='Value'),
        y=alt.Y('density:Q', title='Density'),
        color=alt.Color('type:N', title='Type')
    )
    .properties(width=600, height=400)
)

kde_plot

alt.Chart(...)

In [33]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Assuming cars_data is a DataFrame and it already contains the necessary columns

# Create a subplot with 2 y-axes
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add the horsepower line chart
fig.add_trace(
    go.Scatter(
        x=cars_data['Year'],
        y=cars_data['Horsepower'],
        mode='lines',
        name='Horsepower',
        line=dict(color='blue')
    ),
    secondary_y=False  # Use the primary y-axis
)

# Add the weight line chart
fig.add_trace(
    go.Scatter(
        x=cars_data['Year'],
        y=cars_data['Weight_in_lbs'],
        mode='lines',
        name='Weight in lbs',
        line=dict(color='orange')
    ),
    secondary_y=True  # Use the secondary y-axis
)

# Update layout to customize axes titles and colors
fig.update_layout(
    title='Horsepower and Weight Over Years',
    xaxis_title='Year',
    yaxis_title='Horsepower',
    yaxis2=dict(title='Weight in lbs', titlefont=dict(color='orange'), overlaying='y', side='right'),
    yaxis=dict(title='Horsepower', titlefont=dict(color='blue')),
    width=800,
    height=400
)

# Show the figure
fig.show()